### ISSUE TITLE
Model namespace bug

### ISSUE THREAD

**Issue by 4n70w4** [vemcogroup/nova-charts#1]
Hi! I use Module structure and my models have different namespaces.

But this hardcoded

```php
$modelName = 'App\\'.ucfirst(Str::singular($resource));
```

https://github.com/vemcogroup/nova-charts/blob/ac06fdca4ca5d3edf5c3f15b1ebb7b5927555b84/src/Http/Controllers/ChartController.php#L14

```json
message: "Class 'App\AnotherNamespaceModel' not found"
exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "/var/www/app/vendor/vemcogroup/nova-charts/src/Http/Controllers/ChartController.php"
line: 15
```

**Comment by eldor** [comment]
Released 3.0.0 where you are able to select data model

`->model(App\Models\ModelName);`

Try to see if that works for you
