### ISSUE TITLE
plans to allow chart to appear on index page?

### ISSUE THREAD

**Issue by vesper8** [vemcogroup/nova-charts#3]
It would be great if your charts could also appear on the index page.. do you plan on adding this anytime soon?

Thanks!

**Comment by eldor** [comment]
Hi @vesper8 
What do you mean by on the index page ? Is it for a specific resource?

**Comment by vesper8** [comment]
I have multiple resources where I would like to have a chart appear on the index page. But I was able to accomplish that using https://github.com/coroo/nova-chartjs
