### ISSUE TITLE
insert the graphic in the Resource Detail

### ISSUE THREAD

**Issue by gianmarxWebmapp** [vemcogroup/nova-charts#4]
From the guide I can't figure out where to insert the graph to show it in the Resource Detail?

for example if I enter this code:

`(new \Vemcogroup\Charts\Chart())->selections([2018, 2019, 2020, 2021, 2022]);
`

in the card section of the Resource I find the graph in the Resource index, I would like to understand how to put it in the detail of the resource

**Comment by eldor** [comment]
Hi,

You are able to tell it to only show in the details same way as any card in Nova. `->onlyOnDetail()`
