### ISSUE TITLE
Hello! I have a question

### ISSUE THREAD

**Issue by gakkiismywife** [vemcogroup/nova-charts#5]
I need to set the options. but this project does not make it .

**Comment by eldor** [comment]
Hi @gakkiismywife, we need more information on the issue.

**Comment by gakkiismywife** [comment]
Hi @eldor , I  wanna set the max and min values of the Y-axis. But no way to set them.  
![image](https://user-images.githubusercontent.com/40749544/122887346-64286200-d373-11eb-9196-88eeac4139c8.png)

**Comment by eldor** [comment]
The min and max is based in the values added to chart, so not following the issue?

**Comment by gakkiismywife** [comment]
Yes I kown it based in the values added to chart.  but set the  custom min and max values can make the chart looks clearer.

I saw the chartjs exaple:
`
const config = {
  type: 'line',
  data: data,
  options: {
    responsive: true,
    plugins: {
      title: {
        display: true,
        text: 'Min and Max Settings'
      }
    },
    scales: {
      y: {
        min: 10,
        max: 50,
      }
    }
  },
};
`

**Comment by gakkiismywife** [comment]
And I think the options can make chart more flexible.
Sorry about my poor English.
Thanks for you answer
